export type ContentMode = "family" | "adult";
export type LobbyStatus = "waiting" | "revealing" | "voting" | "results";
export type WordPair = { crew: string; imposter: string; category: string; rating: ContentMode };

export const CATEGORIES = [
  { id: "random", label: "Zufällig", rating: "family" as const },
  { id: "alltag", label: "Alltag", rating: "family" as const },
  { id: "essen", label: "Essen & Trinken", rating: "family" as const },
  { id: "orte", label: "Orte", rating: "family" as const },
  { id: "tiere", label: "Tiere", rating: "family" as const },
  { id: "freizeit", label: "Freizeit", rating: "family" as const },
  { id: "popkultur", label: "Popkultur", rating: "family" as const },
  { id: "nachtleben", label: "Nachtleben 18+", rating: "adult" as const },
  { id: "dating", label: "Dating 18+", rating: "adult" as const },
  { id: "intim", label: "Sex & Intimität 18+", rating: "adult" as const },
  { id: "custom", label: "Eigene Wörter", rating: "family" as const },
];

const family = (category: string, entries: [string, string][]): WordPair[] => entries.map(([crew, imposter]) => ({ crew, imposter, category, rating: "family" }));
const adult = (category: string, entries: [string, string][]): WordPair[] => entries.map(([crew, imposter]) => ({ crew, imposter, category, rating: "adult" }));

// Curated pairs share a setting, function or sensory detail, but differ enough
// for follow-up clues. Avoid synonyms, obvious opposites and obscure vocabulary.
// A category describes the shared theme; individual words may cross categories.
export const WORD_PAIRS: WordPair[] = [
  ...family("alltag", [
    ["Tresor", "Tagebuch"],
    ["Thermoskanne", "Schlafsack"],
    ["Wecker", "Wasserkocher"],
    ["Regenschirm", "Duschvorhang"],
    ["Wäscheklammer", "Haarklammer"],
    ["Spiegel", "Selfie"],
    ["Briefkasten", "Anrufbeantworter"],
    ["Staubsauger", "Föhn"],
    ["Klebeband", "Pflaster"],
    ["Schlüsselbund", "Passwort"],
    ["Sofa", "Hängematte"],
    ["Kühlschrank", "Keller"],
    ["Bügelbrett", "Werkbank"],
    ["Gardine", "Sonnenbrille"],
    ["Zahnbürste", "Flaschenbürste"],
    ["Türklingel", "Benachrichtigung"],
    ["Kissen", "Plüschtier"],
    ["Teppich", "Hausschuhe"],
    ["Schublade", "Rucksack"],
    ["Fernbedienung", "Lichtschalter"],
    ["Kalender", "Stundenplan"],
    ["Einkaufszettel", "Packliste"],
    ["Quittung", "Eintrittskarte"],
    ["Warteschlange", "Stau"],
    ["Umzugskarton", "Reisekoffer"],
    ["Wäschekorb", "Einkaufswagen"],
    ["Fußmatte", "Schuhbürste"],
    ["Rauchmelder", "Küchentimer"],
    ["Korkenzieher", "Bohrmaschine"],
    ["Schere", "Locher"],
    ["Gummiband", "Hosenträger"],
    ["Reißverschluss", "Klettband"],
    ["Schneebesen", "Ventilator"],
    ["Sieb", "Fliegengitter"],
    ["Trichter", "Gießkanne"],
    ["Wärmflasche", "Heizdecke"],
    ["Kühlakku", "Eiswürfel"],
    ["Steckdose", "Tankstelle"],
    ["Verlängerungskabel", "Gartenschlauch"],
    ["Powerbank", "Proviant"],
    ["Besen", "Rechen"],
    ["Schwamm", "Handtuch"],
    ["Radiergummi", "Fleckenentferner"],
    ["Seife", "Spülmittel"],
    ["Badezimmerwaage", "Fieberthermometer"],
    ["Messbecher", "Lineal"],
    ["Taschenlampe", "Kerze"],
    ["Lesebrille", "Lupe"],
    ["Ohrstöpsel", "Schlafmaske"],
    ["Duftkerze", "Weichspüler"],
    ["Tapete", "Geschenkpapier"],
    ["Bilderrahmen", "Schaufenster"],
    ["Pinnwand", "Kühlschranktür"],
    ["Zimmerpflanze", "Aquarium"],
    ["Gartenzwerg", "Türstopper"],
    ["Sparschwein", "Keksdose"],
    ["Nähkasten", "Erste-Hilfe-Kasten"],
    ["Wasserwaage", "Kompass"],
    ["Vorhängeschloss", "Fahrradkette"],
    ["Leiter", "Tritthocker"],
    ["Morgenmantel", "Kuscheldecke"],
    ["Schürze", "Regenjacke"],
    ["Ofenhandschuh", "Boxhandschuh"],
    ["Wäscheleine", "Lichterkette"],
    ["Geschirrspüler", "Autowaschanlage"],
    ["Toaster", "Sonnenbank"],
    ["Mikrowelle", "Heizlüfter"],
    ["Dunstabzug", "Fenster"],
    ["Rollladen", "Garagentor"],
    ["Drehtür", "Drehstuhl"],
    ["Straßenschild", "Namensschild"],
    ["Hausnummer", "Sitzplatznummer"],
    ["Parkuhr", "Spardose"],
    ["Rolltreppe", "Förderband"],
    ["Balkon", "Logenplatz"],
    ["Mülltonne", "Aktenvernichter"],
    ["Pfandautomat", "Münzautomat"],
    ["Waschsalon", "Gemeinschaftsküche"],
    ["Treppenhaus", "Hotelflur"],
    ["Gegensprechanlage", "Babyfon"],
    ["Ladekabel", "Kopfhörerkabel"],
    ["Bildschirmsperre", "Türkette"],
    ["Papierkorb", "Spamordner"],
    ["Fotoalbum", "Adressbuch"],
    ["WLAN", "Radioempfang"],
    ["Drucker", "Kassenzettel"],
    ["Notizzettel", "Lesezeichen"],
    ["Unterschrift", "Fingerabdruck"],
    ["Stempel", "Aufkleber"],
    ["Briefumschlag", "Geschenktüte"],
    ["Ausweis", "Mitgliedskarte"],
    ["Verspätung", "Verschlafen"],
    ["Frühjahrsputz", "Entrümpelung"],
    ["Mittagspause", "Nickerchen"],
    ["Hausordnung", "Spielregeln"],
    ["Nachsendeauftrag", "Rufumleitung"],
    ["Fundsachen", "Flohmarktkiste"],
    ["Schlüsseldienst", "Pannendienst"],
    ["Nachbarschaftshilfe", "Fahrgemeinschaft"],
    ["Stromausfall", "Leerer Akku"],
  ]),
  ...family("essen", [
    ["Popcorn", "Knäckebrot"],
    ["Honig", "Karamell"],
    ["Sushi", "Praline"],
    ["Lasagne", "Sandwich"],
    ["Fondue", "Grillabend"],
    ["Brezel", "Salzstange"],
    ["Kokosnuss", "Ei"],
    ["Granatapfel", "Maiskolben"],
    ["Zitrone", "Essiggurke"],
    ["Avocado", "Butter"],
    ["Tiramisu", "Milchkaffee"],
    ["Zuckerwatte", "Baiser"],
    ["Pfannkuchen", "Tortilla"],
    ["Gnocchi", "Marshmallows"],
    ["Ravioli", "Frühlingsrolle"],
    ["Döner", "Ofenkartoffel"],
    ["Burger", "Bagel"],
    ["Hotdog", "Leberkäsebrötchen"],
    ["Falafel", "Fischstäbchen"],
    ["Risotto", "Milchreis"],
    ["Curry", "Chili con Carne"],
    ["Gazpacho", "Smoothie"],
    ["Brühe", "Tee"],
    ["Kartoffelpüree", "Hummus"],
    ["Pesto", "Guacamole"],
    ["Senf", "Wasabi"],
    ["Meerrettich", "Ingwer"],
    ["Zimt", "Vanille"],
    ["Rosmarin", "Tannennadel"],
    ["Basilikum", "Minze"],
    ["Espresso", "Ingwershot"],
    ["Eistee", "Apfelschorle"],
    ["Mineralwasser", "Brausepulver"],
    ["Kakao", "Pudding"],
    ["Buttermilch", "Sauerkraut"],
    ["Hafermilch", "Mandelmus"],
    ["Orangensaft", "Marmelade"],
    ["Limonade", "Wassereis"],
    ["Bubble Tea", "Wackelpudding"],
    ["Eiskaffee", "Schokoladeneis"],
    ["Croissant", "Windbeutel"],
    ["Donut", "Zwiebelring"],
    ["Waffel", "Toastbrot"],
    ["Brownie", "Energieriegel"],
    ["Käsekuchen", "Panna Cotta"],
    ["Streuselkuchen", "Apfelstrudel"],
    ["Lebkuchen", "Chai"],
    ["Marzipan", "Nougat"],
    ["Rosinen", "Trockenpflaumen"],
    ["Kandierter Apfel", "Schokobanane"],
    ["Lauch", "Staudensellerie"],
    ["Rotkohl", "Rote Bete"],
    ["Pilz", "Aubergine"],
    ["Zucchini", "Avocado"],
    ["Brokkoli", "Petersilie"],
    ["Artischocke", "Spargel"],
    ["Kürbis", "Süßkartoffel"],
    ["Erbse", "Edamame"],
    ["Linsen", "Couscous"],
    ["Kichererbse", "Erdnuss"],
    ["Ananas", "Pinienzapfen"],
    ["Litschi", "Traube"],
    ["Feige", "Dattel"],
    ["Pfirsich", "Aprikosenmarmelade"],
    ["Heidelbeere", "Rotweintraube"],
    ["Wassermelone", "Salatgurke"],
    ["Apfelmus", "Fruchtjoghurt"],
    ["Bananenchips", "Cornflakes"],
    ["Studentenfutter", "Müsli"],
    ["Sonnenblumenkerne", "Pistazien"],
    ["Parmesan", "Semmelbrösel"],
    ["Mozzarella", "Tofu"],
    ["Feta", "Oliven"],
    ["Camembert", "Spiegelei"],
    ["Räucherlachs", "Speck"],
    ["Salami", "Beef Jerky"],
    ["Schnitzel", "Backfisch"],
    ["Hackbällchen", "Kroketten"],
    ["Garnelen", "Calamari"],
    ["Muscheln", "Schnecken"],
    ["Buffet", "Picknick"],
    ["Brunch", "Brotzeit"],
    ["Lunchbox", "Pralinenschachtel"],
    ["Fingerfood", "Plätzchenteller"],
    ["Probierhappen", "Vorspeise"],
    ["Kochrezept", "Backmischung"],
    ["Marinade", "Salatdressing"],
    ["Glasur", "Käsekruste"],
    ["Sauerteig", "Joghurtkultur"],
    ["Einkochen", "Einlegen"],
    ["Dampfgarer", "Reiskocher"],
    ["Mörser", "Kaffeemühle"],
    ["Nudelholz", "Fleischklopfer"],
    ["Spritzbeutel", "Senftube"],
    ["Teebeutel", "Kaffeefilter"],
    ["Strohhalm", "Essstäbchen"],
    ["Suppenkelle", "Eisportionierer"],
    ["Serviette", "Tischdecke"],
    ["Speisekarte", "Zutatenliste"],
    ["Raclette", "Pizzaofen"],
  ]),
  ...family("orte", [
    ["Bibliothek", "Kloster"],
    ["Flughafen", "Messehalle"],
    ["Bahnhof", "Einkaufszentrum"],
    ["Schwimmbad", "Turnhalle"],
    ["Museum", "Schloss"],
    ["Kino", "Planetarium"],
    ["Theater", "Gerichtssaal"],
    ["Supermarkt", "Markthalle"],
    ["Campingplatz", "Schrebergarten"],
    ["Bäckerei", "Hotelküche"],
    ["Leuchtturm", "Aussichtsturm"],
    ["Hafen", "Industriegebiet"],
    ["Baumhaus", "Hochsitz"],
    ["Berghütte", "Leuchtturmwärterhaus"],
    ["Höhle", "Tunnel"],
    ["Wüste", "Salzsee"],
    ["Oase", "Stadtpark"],
    ["Gletscher", "Eishalle"],
    ["Vulkan", "Geysir"],
    ["Schlucht", "Steinbruch"],
    ["Dachboden", "Antiquitätenladen"],
    ["Keller", "Kühlhaus"],
    ["Waschküche", "Labor"],
    ["Garage", "Flugzeughangar"],
    ["Gartenlaube", "Wintergarten"],
    ["Innenhof", "Marktplatz"],
    ["Hinterhof", "Bauhof"],
    ["Treppenhaus", "Parkhaus"],
    ["Fahrstuhl", "Seilbahnkabine"],
    ["Hotelzimmer", "Schiffskabine"],
    ["Wartezimmer", "Flughafengate"],
    ["Apotheke", "Drogerie"],
    ["Krankenhaus", "Pflegeheim"],
    ["Rathaus", "Botschaft"],
    ["Postfiliale", "Paketstation"],
    ["Polizeiwache", "Feuerwache"],
    ["Schule", "Internat"],
    ["Mensa", "Suppenküche"],
    ["Büro", "Lesesaal"],
    ["Archiv", "Lagerhalle"],
    ["Stadion", "Amphitheater"],
    ["Rummelplatz", "Weihnachtsmarkt"],
    ["Zirkuszelt", "Festzelt"],
    ["Aquarium", "Tropenhaus"],
    ["Zoo", "Tierauffangstation"],
    ["Skatepark", "Skisprungschanze"],
    ["Kletterhalle", "Hochseilgarten"],
    ["Minigolfplatz", "Skulpturengarten"],
    ["Escape Room", "Geisterbahn"],
    ["Bowlingbahn", "Spielhalle"],
    ["Strand", "Sandkasten"],
    ["Seeufer", "Flussdelta"],
    ["Insel", "Bohrplattform"],
    ["Wasserfall", "Staudamm"],
    ["Sumpf", "Mangrovenwald"],
    ["Regenwald", "Gewächshaus"],
    ["Steppe", "Golfplatz"],
    ["Korallenriff", "Unterwasserhöhle"],
    ["Obstplantage", "Weinberg"],
    ["Blumenwiese", "Botanischer Garten"],
    ["Pyramide", "Tempel"],
    ["Burgruine", "Ausgrabungsstätte"],
    ["Kathedrale", "Konzerthalle"],
    ["Friedhof", "Gedenkstätte"],
    ["Bunker", "Tresorraum"],
    ["Sternwarte", "Radarkuppel"],
    ["Fernsehturm", "Windrad"],
    ["Stadtmauer", "Deich"],
    ["Brücke", "Schiffsdeck"],
    ["Promenade", "Fußgängerzone"],
    ["Hostel", "Schlafwagen"],
    ["Ferienwohnung", "Hausboot"],
    ["Raststätte", "Bergrastplatz"],
    ["Tankstelle", "Ladestation"],
    ["Fähranleger", "Bushaltestelle"],
    ["Grenzübergang", "Sicherheitskontrolle"],
    ["Reisebüro", "Touristeninformation"],
    ["Souvenirladen", "Fanshop"],
    ["Wochenmarkt", "Flohmarkt"],
    ["Fischmarkt", "Auktionshaus"],
    ["Bauernhof", "Streichelzoo"],
    ["Imkerei", "Baumschule"],
    ["Mühle", "Wasserkraftwerk"],
    ["Sägewerk", "Schreinerei"],
    ["Bergwerk", "U-Bahn-Station"],
    ["Schrottplatz", "Wertstoffhof"],
    ["Filmstudio", "Theaterbühne"],
    ["Tonstudio", "Radiostation"],
    ["Druckerei", "Zeitungsredaktion"],
    ["Großküche", "Kochschule"],
    ["Wolkenkratzer", "Kreuzfahrtschiff"],
    ["Penthouse", "Dachterrasse"],
    ["U-Boot", "Raumstation"],
    ["Forschungscamp", "Basislager"],
    ["Iglu", "Zelt"],
    ["Gefängnis", "Kaserne"],
    ["Schlossgarten", "Skulpturenpark"],
    ["Spiegellabyrinth", "Maislabyrinth"],
    ["Schleuse", "Trockendock"],
    ["Bahnsteig", "Landebahn"],
  ]),
  ...family("tiere", [
    ["Oktopus", "Chamäleon"],
    ["Igel", "Kugelfisch"],
    ["Ameise", "Pinguin"],
    ["Fledermaus", "Delfin"],
    ["Biber", "Termite"],
    ["Pfau", "Kampffisch"],
    ["Schnecke", "Schildkröte"],
    ["Känguru", "Seepferdchen"],
    ["Waschbär", "Otter"],
    ["Eule", "Katze"],
    ["Flamingo", "Garnele"],
    ["Zebra", "Tiger"],
    ["Giraffe", "Strauß"],
    ["Elefant", "Walross"],
    ["Nashorn", "Wildschwein"],
    ["Löwe", "Wolf"],
    ["Gepard", "Windhund"],
    ["Leopard", "Schneeeule"],
    ["Hyäne", "Geier"],
    ["Gorilla", "Braunbär"],
    ["Kamel", "Elefant"],
    ["Lama", "Ziege"],
    ["Alpaka", "Angorakaninchen"],
    ["Rentier", "Husky"],
    ["Hirsch", "Steinbock"],
    ["Gämse", "Wildkatze"],
    ["Murmeltier", "Erdmännchen"],
    ["Stachelschwein", "Seeigel"],
    ["Gürteltier", "Assel"],
    ["Faultier", "Koala"],
    ["Panda", "Koala"],
    ["Braunbär", "Dachs"],
    ["Eisbär", "Polarfuchs"],
    ["Fuchs", "Marder"],
    ["Stinktier", "Tintenfisch"],
    ["Fischotter", "Biber"],
    ["Eichhörnchen", "Eichelhäher"],
    ["Hamster", "Streifenhörnchen"],
    ["Maus", "Spatz"],
    ["Ratte", "Taube"],
    ["Hund", "Papagei"],
    ["Kaninchen", "Reh"],
    ["Meerschweinchen", "Chinchilla"],
    ["Frettchen", "Dackel"],
    ["Schwein", "Nilpferd"],
    ["Pferd", "Kamel"],
    ["Esel", "Dromedar"],
    ["Ziege", "Gazelle"],
    ["Schaf", "Lama"],
    ["Kuh", "Gnu"],
    ["Huhn", "Krokodil"],
    ["Truthahn", "Pfau"],
    ["Ente", "Pinguin"],
    ["Gans", "Wachhund"],
    ["Pelikan", "Walhai"],
    ["Storch", "Reiher"],
    ["Kranich", "Flamingo"],
    ["Adler", "Löwe"],
    ["Falke", "Gepard"],
    ["Specht", "Biber"],
    ["Kolibri", "Hummel"],
    ["Kuckuck", "Elster"],
    ["Rabe", "Elster"],
    ["Amsel", "Frosch"],
    ["Kanarienvogel", "Grille"],
    ["Wellensittich", "Meerschweinchen"],
    ["Tukan", "Papagei"],
    ["Albatros", "Segelfisch"],
    ["Möwe", "Seelöwe"],
    ["Kiwi", "Schnabeltier"],
    ["Hai", "Orca"],
    ["Blauwal", "Mantarochen"],
    ["Robbe", "Seekuh"],
    ["Aal", "Wasserschlange"],
    ["Lachs", "Meeresschildkröte"],
    ["Clownfisch", "Zebrafisch"],
    ["Seestern", "Eidechse"],
    ["Qualle", "Glühwürmchen"],
    ["Krabbe", "Skorpion"],
    ["Hummer", "Hirschkäfer"],
    ["Krokodil", "Anakonda"],
    ["Gecko", "Spinne"],
    ["Leguan", "Landschildkröte"],
    ["Kobra", "Kröte"],
    ["Klapperschlange", "Zikade"],
    ["Frosch", "Heuschrecke"],
    ["Salamander", "Feuerwanze"],
    ["Axolotl", "Kaulquappe"],
    ["Wurm", "Blindschleiche"],
    ["Einsiedlerkrebs", "Schnecke"],
    ["Biene", "Schmetterling"],
    ["Wespe", "Gottesanbeterin"],
    ["Libelle", "Kolibri"],
    ["Marienkäfer", "Dalmatiner"],
    ["Mistkäfer", "Regenwurm"],
    ["Motte", "Fledermaus"],
    ["Zecke", "Blutegel"],
    ["Stechmücke", "Floh"],
    ["Wasserläufer", "Wasserspinne"],
    ["Stabheuschrecke", "Chamäleon"],
  ]),
  ...family("freizeit", [
    ["Schach", "Fechten"],
    ["Bouldern", "Puzzeln"],
    ["Angeln", "Pilze sammeln"],
    ["Surfen", "Snowboarden"],
    ["Yoga", "Ballett"],
    ["Karaoke", "Luftgitarre"],
    ["Bowling", "Minigolf"],
    ["Geocaching", "Schatzsuche"],
    ["Töpfern", "Brot backen"],
    ["Origami", "Papierflieger"],
    ["Fußball", "Eishockey"],
    ["Basketball", "Wasserball"],
    ["Volleyball", "Jonglage"],
    ["Tennis", "Fechtduell"],
    ["Tischtennis", "Airhockey"],
    ["Darts", "Bogenschießen"],
    ["Billard", "Murmelbahn"],
    ["Rugby", "Sumoringen"],
    ["Handball", "Völkerball"],
    ["Baseball", "Brennball"],
    ["Marathon", "Radrennen"],
    ["Hürdenlauf", "Hindernisparcours"],
    ["Hochsprung", "Hochseilartistik"],
    ["Weitsprung", "Skispringen"],
    ["Kugelstoßen", "Kegeln"],
    ["Gewichtheben", "Armdrücken"],
    ["Boxen", "Ringen"],
    ["Judo", "Akrobatik"],
    ["Turnen", "Trampolinspringen"],
    ["Seilspringen", "Stepptanz"],
    ["Schwimmen", "Rudern"],
    ["Tauchen", "Höhlenwandern"],
    ["Schnorcheln", "Vogelbeobachtung"],
    ["Segeln", "Drachensteigen"],
    ["Kajakfahren", "Mountainbiken"],
    ["Rafting", "Achterbahnfahren"],
    ["Wasserski", "Drachenfliegen"],
    ["Stand-up-Paddling", "Slackline"],
    ["Eislaufen", "Inline-Skaten"],
    ["Schlittenfahren", "Seifenkistenrennen"],
    ["Skifahren", "Longboarden"],
    ["Langlauf", "Nordic Walking"],
    ["Schneeschuhwandern", "Wattwandern"],
    ["Bergsteigen", "Expedition"],
    ["Fallschirmspringen", "Bungee-Jumping"],
    ["Gleitschirmfliegen", "Ballonfahren"],
    ["Kartfahren", "Motocross"],
    ["Skateboarden", "Parkour"],
    ["Reiten", "Hundesport"],
    ["Einradfahren", "Jonglieren"],
    ["Gitarre", "Harfe"],
    ["Schlagzeug", "Beatboxen"],
    ["Klavier", "Xylophon"],
    ["Geige", "Singende Säge"],
    ["Flöte", "Mundharmonika"],
    ["Trompete", "Alphorn"],
    ["Akkordeon", "Dudelsack"],
    ["Chor", "Orchester"],
    ["Improvisationstheater", "Freestyle-Rap"],
    ["Zaubertricks", "Bauchreden"],
    ["Malen", "Graffiti"],
    ["Zeichnen", "Tätowieren"],
    ["Schnitzen", "Bildhauerei"],
    ["Nähen", "Modellbau"],
    ["Stricken", "Knüpfen"],
    ["Sticken", "Perlenfädeln"],
    ["Makramee", "Seemannsknoten"],
    ["Kerzenziehen", "Seifengießen"],
    ["Siebdruck", "Stempeln"],
    ["Fotografieren", "Aquarellmalen"],
    ["Gärtnern", "Bonsai"],
    ["Blumen pressen", "Laminieren"],
    ["Muscheln sammeln", "Steine bemalen"],
    ["Briefmarkensammeln", "Panini-Album"],
    ["Sterne beobachten", "Polarlichter suchen"],
    ["Wandern", "Stadtführung"],
    ["Camping", "Trekking"],
    ["Picknick", "Grillen"],
    ["Lagerfeuer", "Fackelwanderung"],
    ["Hängematte", "Liegestuhl"],
    ["Kreuzworträtsel", "Stadt-Land-Fluss"],
    ["Sudoku", "Zauberwürfel"],
    ["Domino", "Jenga"],
    ["Memory", "Ich packe meinen Koffer"],
    ["Mikado", "Dosenwerfen"],
    ["Monopoly", "Die Siedler von Catan"],
    ["Uno", "Mensch ärgere dich nicht"],
    ["Werwolf", "Cluedo"],
    ["Activity", "Improvisation"],
    ["Tabu", "Stille Post"],
    ["Verstecken", "Fangen"],
    ["Gummitwist", "Himmel und Hölle"],
    ["Wasserschlacht", "Lasertag"],
    ["Sandburg", "Schneemann"],
    ["Seifenblasen", "Luftballons"],
    ["Bumerang", "Frisbee"],
    ["Boule", "Curling"],
    ["Wikingerschach", "Hufeisenwerfen"],
    ["Quizabend", "Bingo"],
    ["Lesen", "Hörspiel"],
  ]),
  ...family("popkultur", [
    ["Batman", "James Bond"],
    ["Spider-Man", "Tarzan"],
    ["Superman", "Herkules"],
    ["Hulk", "Werwolf"],
    ["Iron Man", "Inspector Gadget"],
    ["Wonder Woman", "Xena"],
    ["Thor", "Zeus"],
    ["Aquaman", "Poseidon"],
    ["Catwoman", "Lara Croft"],
    ["Joker", "Rumpelstilzchen"],
    ["Harry Potter", "Luke Skywalker"],
    ["Hermine", "Matilda"],
    ["Dumbledore", "Professor X"],
    ["Darth Vader", "Captain Hook"],
    ["Yoda", "Meister Splinter"],
    ["Chewbacca", "Bigfoot"],
    ["R2-D2", "WALL-E"],
    ["E.T.", "Stitch"],
    ["Gollum", "Dobby"],
    ["Frodo", "Alice im Wunderland"],
    ["Sherlock Holmes", "Dr. House"],
    ["Indiana Jones", "Tim und Struppi"],
    ["Robin Hood", "Zorro"],
    ["Jack Sparrow", "Pippi Langstrumpf"],
    ["Peter Pan", "Aladdin"],
    ["Mary Poppins", "Die gute Fee"],
    ["Pinocchio", "Der Zauberer von Oz"],
    ["Rotkäppchen", "Hänsel und Gretel"],
    ["Rapunzel", "Dornröschen"],
    ["Aschenputtel", "Die Schöne und das Biest"],
    ["Shrek", "Grinch"],
    ["SpongeBob", "Minions"],
    ["Patrick Star", "Goofy"],
    ["Donald Duck", "Homer Simpson"],
    ["Dagobert Duck", "Mr. Burns"],
    ["Garfield", "Balu"],
    ["Snoopy", "Gromit"],
    ["Tom und Jerry", "Road Runner"],
    ["Pinky und Brain", "Team Rocket"],
    ["Die Schlümpfe", "Die sieben Zwerge"],
    ["Pikachu", "Sonic"],
    ["Super Mario", "Pac-Man"],
    ["Luigi", "Ron Weasley"],
    ["Prinzessin Peach", "Zelda"],
    ["Kirby", "Staubsauger"],
    ["Donkey Kong", "Obelix"],
    ["Godzilla", "Drache"],
    ["Yoshi", "Ohnezahn"],
    ["Bowser", "Smaug"],
    ["Minecraft", "Lego"],
    ["Tetris", "Tangram"],
    ["Die Sims", "Puppenhaus"],
    ["Animal Crossing", "Stardew Valley"],
    ["Mario Kart", "Autoscooter"],
    ["Pokémon", "Sammelalbum"],
    ["Among Us", "Cluedo"],
    ["Fortnite", "Paintball"],
    ["Just Dance", "Aerobic"],
    ["Guitar Hero", "Karaoke"],
    ["Wii Sports", "Sportfest"],
    ["Zeitmaschine", "Kristallkugel"],
    ["Tarnumhang", "Unsichtbare Tinte"],
    ["Zauberstab", "Fernbedienung"],
    ["Lichtschwert", "Neonröhre"],
    ["Fliegender Teppich", "Heißluftballon"],
    ["Zaubertrank", "Power-up"],
    ["Schatzkarte", "Prophezeiung"],
    ["Portal", "Geheimgang"],
    ["Doppelgänger", "Klon"],
    ["Geist", "Hologramm"],
    ["Zombie", "Mumie"],
    ["Vampir", "Fledermaus"],
    ["Meerjungfrau", "Zentaur"],
    ["Einhorn", "Pegasus"],
    ["Phönix", "Feuerwerk"],
    ["Riese", "Hochhaus"],
    ["Troll", "Oger"],
    ["Elf", "Vulkanier"],
    ["Ninja", "Assassine"],
    ["Pirat", "Weltraumschmuggler"],
    ["Casting", "Vorstellungsgespräch"],
    ["Trailer", "Klappentext"],
    ["Cliffhanger", "Fortsetzungsroman"],
    ["Spoiler", "Lösungsheft"],
    ["Remake", "Coverversion"],
    ["Prequel", "Rückblende"],
    ["Gastauftritt", "Überraschungsbesuch"],
    ["Synchronsprecher", "Bauchredner"],
    ["Stuntdouble", "Stellvertreter"],
    ["Statist", "Chorsänger"],
    ["Roter Teppich", "Laufsteg"],
    ["Autogramm", "Widmung"],
    ["Fanclub", "Ultras"],
    ["Cosplay", "Karneval"],
    ["Comic-Con", "Buchmesse"],
    ["Oscar", "Goldmedaille"],
    ["Eurovision", "Talentshow"],
    ["Ohrwurm", "Werbejingle"],
    ["Meme", "Karikatur"],
    ["Podcast", "Talkshow"],
  ]),
  ...adult("nachtleben", [
    ["Kater", "Jetlag"],
    ["Türsteher", "Flughafenkontrolle"],
    ["Vorglühen", "Soundcheck"],
    ["Afterparty", "Überstunden"],
    ["Gästeliste", "Tischreservierung"],
    ["Einlassstempel", "Festivalbändchen"],
    ["Garderobenmarke", "Pfandchip"],
    ["VIP-Lounge", "Business Class"],
    ["Raucherpause", "Frische Luft"],
    ["Heimweg", "Nachtwanderung"],
    ["Cocktail", "Zaubertrank"],
    ["Tequila", "Mutprobe"],
    ["Absinth", "Kräutermedizin"],
    ["Whisky", "Espresso"],
    ["Champagner", "Feuerwerk"],
    ["Sangria", "Fruchtsalat"],
    ["Glühwein", "Sauna"],
    ["Long Island Iced Tea", "Tarnung"],
    ["Gin Tonic", "Bitterlimonade"],
    ["Bierfass", "Wasserspender"],
    ["Schnapsrunde", "Gruppenumarmung"],
    ["Trinkspiel", "Wahrheit oder Pflicht"],
    ["Beer Pong", "Dosenwerfen"],
    ["Flunkyball", "Staffellauf"],
    ["Bierdeckel", "Visitenkarte"],
    ["Deckel anschreiben", "Ratenzahlung"],
    ["Happy Hour", "Schlussverkauf"],
    ["Letzte Runde", "Zugabe"],
    ["Freigetränk", "Willkommensgeschenk"],
    ["Trinkgeld", "Applaus"],
    ["DJ-Pult", "Cockpit"],
    ["Tanzfläche", "Laufsteg"],
    ["Bass", "Herzschlag"],
    ["Stroboskop", "Gewitter"],
    ["Nebelmaschine", "Dampfbad"],
    ["Discokugel", "Kronleuchter"],
    ["Schwarzlicht", "Neonreklame"],
    ["Konfettikanone", "Laubbläser"],
    ["Leuchtstäbe", "Wunderkerzen"],
    ["Moshpit", "Waschmaschine"],
    ["Polonaise", "Warteschlange"],
    ["Silent Disco", "Videokonferenz"],
    ["Rave", "Marathon"],
    ["Maskenball", "Rollenspiel"],
    ["Kneipentour", "Stadtrundfahrt"],
    ["Junggesellenabschied", "Klassenfahrt"],
    ["Oktoberfest", "Karnevalssitzung"],
    ["Dachparty", "Sonnenuntergang"],
    ["Poolparty", "Schaumparty"],
    ["Karaokebar", "Casting-Show"],
    ["Promille", "Fieberkurve"],
    ["Filmriss", "Gelöschter Chatverlauf"],
    ["Lallende Sprachnachricht", "Verhörer"],
    ["Katerfrühstück", "Mitternachtssnack"],
    ["Verlorene Jacke", "Vertauschter Koffer"],
    ["Leerer Handyakku", "Verpasster Nachtbus"],
    ["Taxischlange", "Check-in"],
    ["Sperrstunde", "Zapfenstreich"],
    ["Nachtruhe", "Ruheabteil"],
    ["Hausverbot", "Rote Karte"],
  ]),
  ...adult("dating", [
    ["Blind Date", "Bewerbungsgespräch"],
    ["Speed Dating", "Casting"],
    ["Datingprofil", "Immobilienanzeige"],
    ["Anmachspruch", "Werbeslogan"],
    ["Flirten", "Pokerface"],
    ["Augenkontakt", "Duell"],
    ["Schmetterlinge im Bauch", "Lampenfieber"],
    ["Erstes Date", "Probefahrt"],
    ["Korb bekommen", "Auswahlverfahren"],
    ["Ghosting", "Funkloch"],
    ["Lovebombing", "Werbeoffensive"],
    ["Eifersucht", "Futterneid"],
    ["Tinder-Match", "Lottogewinn"],
    ["Fernbeziehung", "Brieffreundschaft"],
    ["Situationship", "Probezeit"],
    ["Freundschaft Plus", "Zusatzleistung"],
    ["Offene Beziehung", "Wohngemeinschaft"],
    ["Affäre", "Doppelleben"],
    ["Seitensprung", "Regelbruch"],
    ["One-Night-Stand", "Kurzurlaub"],
    ["Sexting", "Geheimsprache"],
    ["Nacktfoto", "Aktgemälde"],
    ["Booty Call", "Spontanbesuch"],
    ["Walk of Shame", "Verkatertes Frühstück"],
    ["Knutschfleck", "Blauer Fleck"],
    ["Zungenkuss", "Tango"],
    ["Kuscheln", "Wärmflasche"],
    ["Pärchenabend", "Doppelzimmer"],
    ["Wochenendbeziehung", "Pendeln"],
    ["Urlaubsflirt", "Sommerhit"],
    ["Ex-Partner", "Ehemaliger Kollege"],
    ["Trennungsgespräch", "Kündigung"],
    ["Versöhnung", "Waffenstillstand"],
    ["Kontaktpause", "Digital Detox"],
    ["Liebeskummer", "Heimweh"],
    ["Rosenkrieg", "Nachbarschaftsstreit"],
    ["Beziehungspause", "Winterschlaf"],
    ["Schlussmach-Nachricht", "Abschiedsbrief"],
    ["Dating-Frust", "Wohnungssuche"],
    ["Beziehungsstatus", "Wetterbericht"],
    ["Liebesbrief", "Tagebucheintrag"],
    ["Rosenstrauß", "Pralinenschachtel"],
    ["Candle-Light-Dinner", "Stromausfall"],
    ["Überraschungsdate", "Mystery-Box"],
    ["Liebesplaylist", "Duftbrief"],
    ["Partnerlook", "Teamtrikot"],
    ["Kosenamen", "Decknamen"],
    ["Schlüssel tauschen", "Vertrauensvorschuss"],
    ["Zusammenziehen", "Fusion"],
    ["Schwiegereltern", "Prüfungskommission"],
    ["Heiratsantrag", "Bühnenauftritt"],
    ["Verlobungsring", "Siegel"],
    ["Eheversprechen", "Ehrenwort"],
    ["Hochzeitstanz", "Generalprobe"],
    ["Flitterwochen", "Sabbatical"],
    ["Jahrestag", "Gedenktag"],
    ["Paartherapie", "Mediation"],
    ["Beziehungsarbeit", "Gartenpflege"],
    ["Treue", "Stammkundschaft"],
    ["Bindungsangst", "Höhenangst"],
  ]),
  ...adult("intim", [
    ["Vibrator", "Massagepistole"],
    ["Dildo", "Skulptur"],
    ["Analplug", "Ohrstöpsel"],
    ["Liebeskugeln", "Hantel"],
    ["Penisring", "Haargummi"],
    ["Gleitgel", "Massageöl"],
    ["Kondom", "Einweghandschuh"],
    ["Lecktuch", "Frischhaltefolie"],
    ["Handschellen", "Sicherheitsgurt"],
    ["Augenbinde", "Kopfhörer mit Geräuschfilter"],
    ["Fesselspiel", "Kletterseil"],
    ["Bondage", "Makramee"],
    ["Peitsche", "Dirigentenstab"],
    ["Safeword", "Notbremse"],
    ["Fetisch", "Sammelleidenschaft"],
    ["Lederharness", "Klettergurt"],
    ["Latexanzug", "Neoprenanzug"],
    ["Korsett", "Rückenstütze"],
    ["Strapse", "Hosenträger"],
    ["Nippelklemmen", "Wäscheklammern"],
    ["Reizwäsche", "Abendkleid"],
    ["Spitzen-BH", "Spitzengardine"],
    ["Stringtanga", "Bikini"],
    ["Negligé", "Morgenmantel"],
    ["Intimrasur", "Bartpflege"],
    ["Brazilian Waxing", "Pflaster abziehen"],
    ["Schamhaar", "Brusthaar"],
    ["Intimpiercing", "Bauchnabelpiercing"],
    ["Nacktheit", "Ungeschminkt"],
    ["FKK-Strand", "Saunabereich"],
    ["Erektion", "Gänsehaut"],
    ["Orgasmus", "Niesanfall"],
    ["Libido", "Appetit"],
    ["Erregung", "Adrenalin"],
    ["Vorspiel", "Aufwärmtraining"],
    ["Quickie", "Powernap"],
    ["Masturbation", "Meditation"],
    ["Blowjob", "Zungenkuss"],
    ["Cunnilingus", "Massage"],
    ["Handjob", "Handarbeit"],
    ["Oralsex", "Französischer Kuss"],
    ["Analsex", "Vertrauensübung"],
    ["Missionarsstellung", "Blickkontakt"],
    ["Reiterstellung", "Balanceübung"],
    ["Doggy", "Vierfüßlerstand"],
    ["69", "Tandem"],
    ["Löffelchenstellung", "Kuscheln"],
    ["Dreier", "Doppeldate"],
    ["Gruppensex", "Partnertanz"],
    ["Partnertausch", "Platzwechsel"],
    ["Sexfantasie", "Tagtraum"],
    ["Dirty Talk", "Rap-Battle"],
    ["Telefonsex", "Hörspiel"],
    ["Cybersex", "Fernsteuerung"],
    ["Erotisches Rollenspiel", "Improtheater"],
    ["Striptease", "Zaubershow"],
    ["Lapdance", "Privatvorstellung"],
    ["Poledance", "Akrobatik"],
    ["Burlesque", "Revue"],
    ["Nacktmodell", "Schaufensterpuppe"],
    ["Sexshop", "Dessous-Boutique"],
    ["Swingerclub", "Maskenball"],
    ["Stundenhotel", "Wellness-Suite"],
    ["Rotlichtviertel", "Vergnügungspark"],
    ["Porno", "Videotutorial"],
    ["Pornodarsteller", "Stuntdouble"],
    ["Sexspielzeug", "Fitnessgerät"],
    ["Lustschaukel", "Hängesessel"],
    ["Wasserbett", "Luftmatratze"],
    ["Spiegeldecke", "Selfiekamera"],
    ["Penis", "Zunge"],
    ["Vulva", "Aktzeichnung"],
    ["Klitoris", "G-Punkt"],
    ["Brustwarze", "Ohrläppchen"],
    ["Sperma", "Gleitmittel"],
    ["Nachspiel", "Abkühlen"],
    ["Aftercare", "Wellness"],
    ["Sexflaute", "Sommerloch"],
    ["Verhütung", "Sicherheitsnetz"],
    ["Sex im Freien", "Wildcampen"],
  ]),
];

export function normalizeName(value: string) { return value.normalize("NFKC").trim().replace(/\s+/g, " ").toLocaleLowerCase("de"); }
export function defaultImposterCount(players: number) { return Math.max(1, Math.min(4, Math.floor((players + 2) / 5))); }
export function maxImposterCount(players: number) { return Math.max(1, Math.ceil(players / 2) - 1); }
